name: Watches
favicon: null
layout_spectrum: 0.9774187114089727
typography_spectrum: 0.4617384225130081
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4823064517695457
  lightness: 0.19308210629969835
  saturation: 0.09269000496715307
  rhythmicContrast: 0.6299147792160511
purpose: []
